# Generated by Django 4.2.5 on 2023-10-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclass',
            name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.DeleteModel(
            name='EnrolledUser',
        ),
        migrations.DeleteModel(
            name='MyClass',
        ),
    ]
