# Generated by Django 4.2.7 on 2023-11-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0003_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="question_responses",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="Response",
        ),
    ]
