# Generated by Django 4.2.5 on 2023-10-04 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_quiz_num1_quiz_num2_quiz_num3_quiz_num4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.discussion'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
