# Generated by Django 4.2.6 on 2023-11-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0004_quiz_question_responses_delete_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="grade",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
