# Generated by Django 4.2.6 on 2023-11-07 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0008_alter_grade_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="question_responses",
        ),
    ]
