# Generated by Django 4.2.7 on 2023-11-07 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0009_remove_quiz_question_responses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teachers.quiz"
            ),
        ),
    ]
